POST http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": "VS code rest client is a pretty handy tool",
  "important": true,
  "id": ""
}

###
GET http://localhost:3001/api/notes/

###
GET http://localhost:3001/api/notes/222

###
DELETE http://localhost:3001/api/notes/22